### ISSUE TITLE
crm_node -l produces different putput depending on underlying cluster infrastructure

### ISSUE THREAD

**Issue by fdanapfel** [fmherschel/SAPHanaSR-old-private#1]
crm_node -l output is different for RHEL6 (cman) and SLES11 (openais/corosync):

SLES11:
sles11n1:~ # crm_attribute --type crm_config --name  cluster-infrastructure -q
classic openais (with plugin)
sles11n1:~ # crm_node -l
123456789 sles11n1 member
123456790 sles11n2 member

RHEL6:
[root@rhel6 ~]# crm_attribute --type crm_config --name  cluster-infrastructure -q
cman
[root@rhel6 ~]# crm_node -l
rhel6n1 rhel6n2

**Comment by fmherschel** [comment]
Maybe we need to add more cases, for the situation SLES12 or RHEL would return something different than "classic openais (with plugin)" or "cman". Do you have the return value for RHEL7 already? Will it be still cman or something different?

**Comment by fdanapfel** [comment]
I don't have a RHEL7 cluster available right now to check. But when I have I'll add the necessary code.

**Comment by fmherschel** [comment]
Same for me with SLES12 ;-)

**Comment by fmherschel** [comment]
solved for sles11sp3 and rhel6,5 with current commits in suse / redhat and master branch

**Comment by fmherschel** [comment]
closing
