### ISSUE TITLE
Current sync mode get's lost during switchover

### ISSUE THREAD

**Issue by fdanapfel** [fmherschel/SAPHanaSR-old-private#16]
If system replication is runnig with mode "syncmem" and a switchover occurs the sync mode is reset to "sync".

**Comment by fmherschel** [comment]
Yes. We need to change the recovery procedure in the resource agents for the case when exactly we have two primaries (also during sr_takeover). In this case no instance could dertermine the syncmode from hdbnsutils any more ans we should NOT change the already known mode value.

**Comment by fmherschel** [comment]
Unfortunately the "sync" is the value during the takeover of the former secondary :/ This means the SAP interface hdbnsutil does not report the correct value right after the begin of the takeover. This forces the SAPHanaTopology RA to mark-up the "sync" value in the attribute. Later on SAPHana takes this value from the attribute store and uses it for the registration.
In sum this means we would need a more stable interface from SAP. Or we would need to implement one more workarround.

**Comment by fmherschel** [comment]
Do we have a new status from SAP for that one?

**Comment by fdanapfel** [comment]
According to latest info received from SAP the bug will be fixed with the next revisions of SAP HANA SPS9 and SPS10 (97.01 and 101). Fix will not be included in SPS8.
