### ISSUE TITLE
Resource agent causes error "Could not map name=<remote hostname> to a UUID" to be logged continuously

### ISSUE THREAD

**Issue by fdanapfel** [fmherschel/SAPHanaSR-old-private#18]
The error is due to a "remoteHost" being used instead of "remoteNode" in an get_attributes call.

**Comment by fmherschel** [comment]
Thanks for the issue report and even more for your code change tip :)
This issue should already be addressed with the following commit (already upstream and mergerd in master)
https://github.com/fmherschel/SAPHanaSR/commit/662b60e6efefee1206bd153e41b587f03b332eaa
