### ISSUE TITLE
Nodename is not necessarily always identical to hostname 

### ISSUE THREAD

**Issue by fdanapfel** [fmherschel/SAPHanaSR-old-private#2]
For example on  cluster setups where cman is used the nodenames will always be different from the hostnames if a separate network is used for the cluster communication:

[root@rhel6 ~]# hostname
rhel6
[root@rhel6 ~]# crm_attribute --type crm_config --name  cluster-infrastructure -q
cman
[root@rhel6 ~]# crm_node -n
rhel6hb

**Comment by fmherschel** [comment]
Yes we should take "crm_node -n" output into account and maybe we could use $HOSTNAME as a last fall back.

**Comment by fmherschel** [comment]
solved via your and my changes
