### ISSUE TITLE
Monitor error - rc1: command not found

### ISSUE THREAD

**Issue by iugrifma** [fmherschel/SAPHanaSR-old-private#29]
Hi Fabian,
I think there is a small syntax error on line 908 of the SAPHana agent.
I have observed a stderr in the /var/log/messages file (picture enclosed) and investigation shows 908 to be rc1, should this be rc=1 ?

Kind regards,
Martin.
![fabian_error_2](https://cloud.githubusercontent.com/assets/13434756/11088864/b777b4c4-8865-11e5-8180-6771ee3f0da9.png)

**Comment by fmherschel** [comment]
Yes this a known bug and already fixed in the internal repositories. After testing with other changes it will be upstream and also available via official update channels.
