### ISSUE TITLE
show_SAPHanaSR_attributes outputs NULL

### ISSUE THREAD

**Issue by iugrifma** [fmherschel/SAPHanaSR-old-private#30]
Hi Fabian,
I have noticed that the test script show_SAPHanaSR_attributes is no longer returning any output.
Picture included. This is on SUSE 11 SP3, HANA 102 (though I have seen same behaviour on SP9).

Regards,
Martin.
![fabian_error_1](https://cloud.githubusercontent.com/assets/13434756/11088919/2520c696-8866-11e5-97b2-eeba60454d04.PNG)

**Comment by fmherschel** [comment]
My guess is that you have multiple HANAs isntalled, so the script could not detect the one-and-only :) Could you try to provide the sid via command line?
show_SAPHanaSR_attributes --sid=<YourHsrSID> # YourHsrSID is the SID of the replicated HANA 
Example: show_SAPHanaSR_attributes --sid=SLE  # (or whatever)

**Comment by fmherschel** [comment]
Closing the issue due to no anser.
