### ISSUE TITLE
Agent support for HANA SP11

### ISSUE THREAD

**Issue by iugrifma** [fmherschel/SAPHanaSR-old-private#33]
Dear Fabian, Hi ! 
I am currently implementing the agent for the first time on SP11. I have noticed a small issue, which may be worth considering. When the agent tries to perform an sr_register command I am seeing a failure (please see screenshot attached). I think this is due to deprecated registration parameter --mode= . See below: 
![hanasr_error_1](https://cloud.githubusercontent.com/assets/13434756/12942152/fa5cdbec-cfd8-11e5-8eda-9f90db8d764e.PNG)

As a temporary measure I had adjusted the agent register command(s) to be SP11 friendly.
![hanasr_fix_1](https://cloud.githubusercontent.com/assets/13434756/12942186/42529cb6-cfd9-11e5-956e-b0799de50d1a.PNG)

However, I only "hardcoded" the additional operation mode parameter. Would it be possible it add functionality within the agent's configurable parameters, to allow someone to set the replication operation mode [delta_datashipping | logreplay ] ?

Many thanks, regards,
Martin. (Dell).

**Comment by fmherschel** [comment]
Yes we already have a patched version of the RA. However we never have seen that the register FAILS once we where using the deprecated parameters. SAP has told us, that the old parameters are still 100%
usable and our tests have shown that it works with SPS11.
On the other side we also want to support the new operation Mode (log shipping) and thus need to figure that out correctly from SAP HANA. We already have a patch candidate for that but it is not ready tested so far.

**Comment by fmherschel** [comment]
Sorry I ment logreplay of course :)

**Comment by fmherschel** [comment]
And one thing more to add: Why are you using "async" for the automated system replication takeover? This could result into data loss in my opinion. My guess is that with async you could lead into older data, because the primary does not hold the commits. So I do not recommend this setting!

**Comment by iugrifma** [comment]
Hi Fabian, When do you expect the patched version of the RA to be on general release ?
Do you know yet what the version number will be ? (So I can keep an eye out for it).
TNX.

BTW using async as its a cost optimised solution (rep presisting to disk only).

**Comment by fmherschel** [comment]
> BTW using async as its a cost optimised solution (rep presisting to disk only).
> async has NOTHING to do with cost optimized or "syncing to disk only". Async says, that the primary does NOT hold any commit till the secondary acks the commit been copied to memory or disk (sync/syncmem). However as you correctly understood not all changes are loaded to memory and are send to the peristance layer anyhow. But async is the wrong answer to "syncing to disk only".

**Comment by fmherschel** [comment]
About versions: 0.152 will be the fixed version. For production envireonments you ALWAYS need the official packages by your Linux vendor. Never use this upstream RAs and claiming any problems in productive environments.
