### ISSUE TITLE
Stale cluster attribute for operation_mode

### ISSUE THREAD

**Issue by jh23453** [fmherschel/SAPHanaSR-old-private#36]
We've just migrated our production system into HANA and are using
system replication. At first we ran with replicationmode=syncmem and
operationmode=logreplay, but hit SAP note 2329460. Since we  
already had users on our system we switched to operationmode
delta_datashipping. We did (still running production on our primary):
- Cluster in maintainance mode
- unregister secondary with hdbnsutil -sr_unregister
- re-register secondary with hdbnsutil -sr_register --operationMode=delta_datashipping
- After the resync we took the cluster out of maintainance mode

After these steps we have a working system replication and Linux cluster,
but inconsistencies between the running config, global.ini,
and what the cluster thinks about our system.

Let's have a look at the global.ini first. On the primary node we still
have (-sr_unregister didn't change this):

[system_replication]
operation_mode=logreplay

On the secondary we have (changed by -sr_register):

[system_replication]
operation_mode=delta_datashipping

This configuration is reflected in the cluster attributes. Primary
node has logreplay in hana_<sid>_op_mode. Secondary has delta_datashipping
in there - we had expected to find the same value in both nodes.

The reason for this is in line 2292 in SAPHana:

```
        # TODO: PRIO 3: check, if using getParameter.py is the best option to analyze the set operationMode
        # DONE: PRIO 3: Should we default to logreplay for SAP HANA >= SPS11 ?
        hanaOut1=$(HANA_CALL --timeout 10 --use-su --cmd "getParameter.py --key=global.ini/system_replication/operation_mode --sapcontrol=1")
        hanaFilter1=$(echo "$hanaOut1" | awk -F/ 'BEGIN {out=0} /^SAPCONTROL-OK: <begin>/ { out=1 } /^SAPCONTROL-OK: <end>/ { out=0 } /=/ {if (out==1) {print $3} }')
        hanaOM=$(echo "$hanaFilter1" | awk -F= '$1=="operation_mode" {print $2}')
        set_hana_attribute ${NODENAME} "$hanaOM" ${ATTR_NAME_HANA_OPERATION_MODE[@]}
```

Here we read the (stale) config from global.ini. The only command
to find the currently running configuration seems to be 

> hdbcons -e hdbindexserver 'replication info'

I didn't find an SQL command or any other command.
I have no idea if the output of hdbindexserver is stable
and can be used. I also agree that the situation is pretty unusual
and will be fixed by a short downtime and changes in global.ini.

Anyway, here's a preliminary and untested patch that should help:
[I'll confirm or send an updated patch after we've verified it
on a testcluster or during the next planned downtime]

```
--- SAPHana.orig        2016-09-06 12:27:10.000000000 +0200
+++ SAPHana     2016-09-06 12:33:20.000000000 +0200
@@ -2289,9 +2289,8 @@
             local hanaOut1=""
             # TODO: PRIO 3: check, if using getParameter.py is the best option to analyze the set OperationMode
             # DONE: PRIO 3: Should we default to logreplay for SAP HANA >= SPS11 ?
-            hanaOut1=$(HANA_CALL --timeout 10 --use-su --cmd "getParameter.py  --key=global.ini/system_replication/operation_mode --sapcontrol=1")
-            hanaFilter1=$(echo "$hanaOut1" | awk -F/ 'BEGIN {out=0} /^SAPCONTROL-OK: <begin>/ { out=1 } /^SAPCONTROL-OK: <end>/ { out=0 } /=/ {if (out==1) {print $3} }')
-            hanaOM=$(echo "$hanaFilter1" | awk -F= '$1=="operation_mode" {print $2}')
+            hanaOut1=$(HANA_CALL --timeout 10 --use-su --cmd "hdbcons -e hdbindexserver 'replication info'")
+            hanaOM=$(echo "$hanaOut1" | awk 'OperationMode { print $4 }')
             set_hana_attribute ${NODENAME} "$hanaOM" ${ATTR_NAME_HANA_OPERATION_MODE[@]}
             super_ocf_log debug "DBG: sync_attr=$sync_attr"
             case "$sync_attr" in
```

Any comments?

**Comment by fmherschel** [comment]
As this is a _productive_ system (as you mentioned) - please open a service request (SR) at SUSE support or a SAP ticket at component BC:OP:LNX:SUSE. We could then more easy formalize the process that you get a PTF version, if we could reproduce the bug.

And thanks for reporting that issue here. Of course I will have a look on the problem, but only the official process could provide you with an update in special for productive systems.

And (sorry for updating again my comment) - could you ask SAP, if there is a command to "push" down the changed operation mode to global.ini even when keeping the SAP HANA running? In such a case we could just add the "push-down" command after the re-registration.

**Comment by jh23453** [comment]
We already have a ticket open and our system up and running :-) I'll connect the ticket to this discussion.

I think the "push-down" option might be useful or another means to get the current state easily.
That's exactly why I just asked for comments - to get a discussion going what might be changed or how.
Let's see what the SAP people might think.

**Comment by fmherschel** [comment]
If I remember correctly we first used the method to get the OM from the global.ini instead of the hdbcons, because that call was added later. Maybe we would again need to add a case statement to differ SAP revisions around SPS11.

**Comment by jh23453** [comment]
I guess we should close the issue - changing OM should be rare, and a HANA restart most likely a good idea.
If you disagree feel free to reopen.
