### ISSUE TITLE
Secure store users are hardcoded

### ISSUE THREAD

**Issue by fdanapfel** [fmherschel/SAPHanaSR-old-private#4]
The secure store users in the SAPHana resource agent are currently hardcoded. Would be nice if this was configurable.

**Comment by fmherschel** [comment]
The secure store users are only neede for SAP HANA Workloads < SPS9. With SPS9 there will eb a new interface (python script) which makes secstore obsolete for the RA. Adding a parameter for only a short period if time is sub-optimal.

**Comment by fdanapfel** [comment]
OK, could we then at least make the name a bit more generic? :-)

**Comment by fmherschel** [comment]
I would vote for the following as we already have installations outside. Let us use the todays implemented user key name and if that one is not found the resource agent asks for a second one. This one would be named "SAPHANASR" - would that be acceptable?

**Comment by fmherschel** [comment]
solved by your commits so we have at least two userkeys.
