### ISSUE TITLE
DB couldn't be monitored within 60 seconds hard coded in SAPHana Agent

### ISSUE THREAD

**Issue by khokarv** [fmherschel/SAPHanaSR-old-private#46]
We have two node cluster on RHEL7.2 pacemaker cluster. DB monitoring is failing which is leading to crash of Node B. Though backup is happening on Node A. if we run #time pcs resource debug-monitor rsc_Topology_HDB_HDB00, comes back in 48 to 120 seconds sometime. 

-bash-4.2# timeout 60 su - hb1adm -c 'true; /usr/sap/HB1/HDB00/HDBSettings.sh landscapeHostConfiguration.py'
| Host       | Host   | Host   | Failover | Remove | Storage   | Storage   | Failover | Failover | NameServer | NameServer | IndexServer | IndexServer | Host   | Host   | Worker  | Worker  |
|            | Active | Status | Status   | Status | Config    | Actual    | Config   | Actual   | Config     | Actual     | Config      | Actual      | Config | Actual | Config  | Actual  |
|            |        |        |          |        | Partition | Partition | Group    | Group    | Role       | Role       | Role        | Role        | Roles  | Roles  | Groups  | Groups  |
| ---------- | ------ | ------ | -------- | ------ | --------- | --------- | -------- | -------- | ---------- | ---------- | ----------- | ----------- | ------ | ------ | ------- | ------- |
| HANAHOST | yes    | ok     |          |        |         1 |         1 | default  | default  | master 1   | master     | worker      | master      | worker | worker | default | default |
 
Session terminated, killing shell... ...killed.
-bash-4.2# echo $?
124
-bash-4.2#

Here is my pacemaker cluster configuration:
# cat /var/lib/pacemaker/cib/cib.xml
<cib crm_feature_set="3.0.10" validate-with="pacemaker-2.5" epoch="319915" num_updates="0" admin_epoch="0" cib-last-written="Thu May  3 15:25:05 2018" update-origin="NodeB-int" update-client="crm_attribute" update-user="root" have-quorum="1" dc-uuid="1">
  <configuration>
    <crm_config>
      <cluster_property_set id="cib-bootstrap-options">
        <nvpair id="cib-bootstrap-options-have-watchdog" name="have-watchdog" value="false"/>
        <nvpair id="cib-bootstrap-options-dc-version" name="dc-version" value="1.1.15-11.el7_3.4-e174ec8"/>
        <nvpair id="cib-bootstrap-options-cluster-infrastructure" name="cluster-infrastructure" value="corosync"/>
        <nvpair id="cib-bootstrap-options-cluster-name" name="cluster-name" value="hanacvip210"/>
        <nvpair id="cib-bootstrap-options-last-lrm-refresh" name="last-lrm-refresh" value="1501673365"/>
        <nvpair id="cib-bootstrap-options-maintenance-mode" name="maintenance-mode" value="false"/>
        <nvpair id="cib-bootstrap-options-enable-acl" name="enable-acl" value="true"/>
      </cluster_property_set>
    </crm_config>
    <nodes>
      <node id="1" uname="NodeA-int">
        <instance_attributes id="nodes-1">
          <nvpair id="nodes-1-hana_vin_vhost" name="hana_vin_vhost" value="NodeA"/>
          <nvpair id="nodes-1-hana_vin_site" name="hana_vin_site" value="VINCF64_PRIMARY"/>
          <nvpair id="nodes-1-hana_vin_remoteHost" name="hana_vin_remoteHost" value="NodeB"/>
          <nvpair id="nodes-1-lpa_vin_lpt" name="lpa_vin_lpt" value="30"/>
          <nvpair id="nodes-1-hana_vin_srmode" name="hana_vin_srmode" value="syncmem"/>
          <nvpair id="nodes-1-hana_vin_op_mode" name="hana_vin_op_mode" value="logreplay_readaccess"/>
        </instance_attributes>
      </node>
      <node id="2" uname="NodeB-int">
        <instance_attributes id="nodes-2">
          <nvpair id="nodes-2-lpa_vin_lpt" name="lpa_vin_lpt" value="1525386305"/>
          <nvpair id="nodes-2-hana_vin_vhost" name="hana_vin_vhost" value="NodeB"/>
          <nvpair id="nodes-2-hana_vin_remoteHost" name="hana_vin_remoteHost" value="NodeA"/>
          <nvpair id="nodes-2-hana_vin_site" name="hana_vin_site" value="VINCF65_SECONDARY"/>
          <nvpair id="nodes-2-hana_vin_srmode" name="hana_vin_srmode" value="syncmem"/>
          <nvpair id="nodes-2-hana_vin_op_mode" name="hana_vin_op_mode" value="logreplay_readaccess"/>
        </instance_attributes>
      </node>
    </nodes>
    <resources>
      <primitive class="ocf" id="rsc_VIN_HDB00" provider="heartbeat" type="IPaddr2">
        <instance_attributes id="rsc_VIN_HDB00-instance_attributes">
          <nvpair id="rsc_VIN_HDB00-instance_attributes-ip" name="ip" value="10.14.200.66"/>
        </instance_attributes>
        <operations>
          <op id="rsc_VIN_HDB00-start-interval-0s" interval="0s" name="start" timeout="20s"/>
          <op id="rsc_VIN_HDB00-stop-interval-0s" interval="0s" name="stop" timeout="20s"/>
          <op id="rsc_VIN_HDB00-monitor-interval-10s" interval="10s" name="monitor" timeout="20s"/>
        </operations>
        <meta_attributes id="rsc_VIN_HDB00-meta_attributes"/>
      </primitive>
      <clone id="rsc_Topology_VIN_HDB00-clone">
        <primitive class="ocf" id="rsc_Topology_VIN_HDB00" provider="heartbeat" type="SAPHanaTopology">
          <instance_attributes id="rsc_Topology_VIN_HDB00-instance_attributes">
            <nvpair id="rsc_Topology_VIN_HDB00-instance_attributes-SID" name="SID" value="VIN"/>
            <nvpair id="rsc_Topology_VIN_HDB00-instance_attributes-InstanceNumber" name="InstanceNumber" value="00"/>
            <nvpair id="rsc_Topology_VIN_HDB00-instance_attributes-trace_ra" name="trace_ra" value="1"/>
          </instance_attributes>
          <operations>
            <op id="rsc_Topology_VIN_HDB00-start-interval-0s" interval="0s" name="start" timeout="600"/>
            <op id="rsc_Topology_VIN_HDB00-stop-interval-0s" interval="0s" name="stop" timeout="300"/>
            <op id="rsc_Topology_VIN_HDB00-monitor-interval-60" interval="60" name="monitor" timeout="600"/>
          </operations>
          <meta_attributes id="rsc_Topology_VIN_HDB00-meta_attributes"/>
        </primitive>
        <meta_attributes id="rsc_Topology_VIN_HDB00-clone-meta_attributes">
          <nvpair id="rsc_Topology_VIN_HDB00-clone-meta_attributes-clone-max" name="clone-max" value="2"/>
          <nvpair id="rsc_Topology_VIN_HDB00-clone-meta_attributes-clone-node-max" name="clone-node-max" value="1"/>
          <nvpair id="rsc_Topology_VIN_HDB00-clone-meta_attributes-interleave" name="interleave" value="true"/>
        </meta_attributes>
      </clone>
      <master id="msl_rsc_Hana_VIN_HDB00">
        <primitive class="ocf" id="rsc_Hana_VIN_HDB00" provider="heartbeat" type="SAPHana">
          <instance_attributes id="rsc_Hana_VIN_HDB00-instance_attributes">
            <nvpair id="rsc_Hana_VIN_HDB00-instance_attributes-SID" name="SID" value="VIN"/>
            <nvpair id="rsc_Hana_VIN_HDB00-instance_attributes-InstanceNumber" name="InstanceNumber" value="00"/>
            <nvpair id="rsc_Hana_VIN_HDB00-instance_attributes-PREFER_SITE_TAKEOVER" name="PREFER_SITE_TAKEOVER" value="true"/>
            <nvpair id="rsc_Hana_VIN_HDB00-instance_attributes-DUPLICATE_PRIMARY_TIMEOUT" name="DUPLICATE_PRIMARY_TIMEOUT" value="7200"/>
            <nvpair id="rsc_Hana_VIN_HDB00-instance_attributes-AUTOMATED_REGISTER" name="AUTOMATED_REGISTER" value="true"/>
            <nvpair id="rsc_Hana_VIN_HDB00-instance_attributes-trace_ra" name="trace_ra" value="1"/>
          </instance_attributes>
          <operations>
            <op id="rsc_Hana_VIN_HDB00-start-interval-0s" interval="0s" name="start" timeout="3600"/>
            <op id="rsc_Hana_VIN_HDB00-stop-interval-0s" interval="0s" name="stop" timeout="3600"/>
            <op id="rsc_Hana_VIN_HDB00-promote-interval-0s" interval="0s" name="promote" timeout="3600"/>
            <op id="rsc_Hana_VIN_HDB00-demote-interval-0s" interval="0s" name="demote" timeout="3600"/>
            <op id="rsc_Hana_VIN_HDB00-monitor-interval-59" interval="59" name="monitor" role="Master" timeout="700"/>
            <op id="rsc_Hana_VIN_HDB00-monitor-interval-61" interval="61" name="monitor" role="Slave" timeout="700"/>
            <op id="rsc_Hana_VIN_HDB00-monitor-interval-60s" interval="60s" name="monitor" on-fail="fence" timeout="700"/>
          </operations>
          <meta_attributes id="rsc_Hana_VIN_HDB00-meta_attributes"/>
        </primitive>
        <meta_attributes id="msl_rsc_Hana_VIN_HDB00-meta_attributes">
          <nvpair id="msl_rsc_Hana_VIN_HDB00-meta_attributes-interleave" name="interleave" value="true"/>
          <nvpair id="msl_rsc_Hana_VIN_HDB00-meta_attributes-clone-max" name="clone-max" value="2"/>
          <nvpair id="msl_rsc_Hana_VIN_HDB00-meta_attributes-notify" name="notify" value="true"/>
          <nvpair id="msl_rsc_Hana_VIN_HDB00-meta_attributes-clone-node-max" name="clone-node-max" value="1"/>
        </meta_attributes>
      </master>
      <primitive class="stonith" id="st_ilo_NodeA-int" type="fence_ilo4">
        <instance_attributes id="st_ilo_NodeA-int-instance_attributes">
          <nvpair id="st_ilo_NodeA-int-instance_attributes-ipaddr" name="ipaddr" value="192.168.1.1"/>
          <nvpair id="st_ilo_NodeA-int-instance_attributes-login" name="login" value="clusteruser"/>
          <nvpair id="st_ilo_NodeA-int-instance_attributes-action" name="action" value="reboot"/>
          <nvpair id="st_ilo_NodeA-int-instance_attributes-pcmk_host_list" name="pcmk_host_list" value="NodeA-int"/>
          <nvpair id="st_ilo_NodeA-int-instance_attributes-passwd_script" name="passwd_script" value="/usr/local/bin/pcs-ilo-decrypt-passwd"/>
          <nvpair id="st_ilo_NodeA-int-instance_attributes-passwd" name="passwd" value=""/>
        </instance_attributes>
        <operations>
          <op id="st_ilo_NodeA-int-monitor-interval-60s" interval="60s" name="monitor"/>
        </operations>
      </primitive>
      <primitive class="stonith" id="st_ilo_NodeB-int" type="fence_ilo4">
        <instance_attributes id="st_ilo_NodeB-int-instance_attributes">
          <nvpair id="st_ilo_NodeB-int-instance_attributes-ipaddr" name="ipaddr" value="192.168.1.2"/>
          <nvpair id="st_ilo_NodeB-int-instance_attributes-login" name="login" value="clusteruser"/>
          <nvpair id="st_ilo_NodeB-int-instance_attributes-action" name="action" value="reboot"/>
          <nvpair id="st_ilo_NodeB-int-instance_attributes-pcmk_host_list" name="pcmk_host_list" value="NodeB-int"/>
          <nvpair id="st_ilo_NodeB-int-instance_attributes-passwd_script" name="passwd_script" value="/usr/local/bin/pcs-ilo-decrypt-passwd"/>
          <nvpair id="st_ilo_NodeB-int-instance_attributes-passwd" name="passwd" value=""/>
          <nvpair id="st_ilo_NodeB-int-instance_attributes-delay" name="delay" value="6"/>
        </instance_attributes>
        <operations>
          <op id="st_ilo_NodeB-int-monitor-interval-60s" interval="60s" name="monitor"/>
        </operations>
        <meta_attributes id="st_ilo_NodeB-int-meta_attributes"/>
      </primitive>
      <primitive class="lsb" id="mon_ilo_NodeA-int" type="mon_ilo_NodeA-int">
        <instance_attributes id="mon_ilo_NodeA-int-instance_attributes"/>
        <operations>
          <op id="mon_ilo_NodeA-int-start-interval-0s" interval="0s" name="start" timeout="600"/>
          <op id="mon_ilo_NodeA-int-stop-interval-0s" interval="0s" name="stop" timeout="600"/>
          <op id="mon_ilo_NodeA-int-monitor-interval-300" interval="300" name="monitor" on-fail="block" timeout="600"/>
        </operations>
      </primitive>
      <primitive class="lsb" id="mon_ilo_NodeB-int" type="mon_ilo_NodeB-int">
        <instance_attributes id="mon_ilo_NodeB-int-instance_attributes"/>
        <operations>
          <op id="mon_ilo_NodeB-int-start-interval-0s" interval="0s" name="start" timeout="600"/>
          <op id="mon_ilo_NodeB-int-stop-interval-0s" interval="0s" name="stop" timeout="600"/>
          <op id="mon_ilo_NodeB-int-monitor-interval-300" interval="300" name="monitor" on-fail="block" timeout="600"/>
        </operations>
      </primitive>
    </resources>
    <constraints>
      <rsc_colocation id="colocation-rsc_VIN_HDB00-msl_rsc_Hana_VIN_HDB00-2000" rsc="rsc_VIN_HDB00" rsc-role="Started" score="2000" with-rsc="msl_rsc_Hana_VIN_HDB00" with-rsc-role="Master"/>
      <rsc_order first="rsc_Topology_VIN_HDB00-clone" first-action="start" id="order-rsc_Topology_VIN_HDB00-clone-msl_rsc_Hana_VIN_HDB00-mandatory" symmetrical="false" then="msl_rsc_Hana_VIN_HDB00" then-action="start"/>
      <rsc_location id="location-st_ilo_NodeA-int-NodeA-int--INFINITY" node="NodeA-int" rsc="st_ilo_NodeA-int" score="-INFINITY"/>
      <rsc_location id="location-st_ilo_NodeB-int-NodeB-int--INFINITY" node="NodeB-int" rsc="st_ilo_NodeB-int" score="-INFINITY"/>
      <rsc_location id="location-mon_ilo_NodeA-int-NodeB-int--INFINITY" node="NodeB-int" rsc="mon_ilo_NodeA-int" score="-INFINITY"/>
      <rsc_location id="location-mon_ilo_NodeB-int-NodeA-int--INFINITY" node="NodeA-int" rsc="mon_ilo_NodeB-int" score="-INFINITY"/>
    </constraints>
    <rsc_defaults>
      <meta_attributes id="rsc_defaults-options"/>
    </rsc_defaults>
    <op_defaults>
      <meta_attributes id="op_defaults-options">
        <nvpair id="op_defaults-options-timeout" name="timeout" value="600s"/>
      </meta_attributes>
    </op_defaults>
    <acls>
      <acl_role description="Read access to cluster" id="read-only">
        <acl_permission id="read-only-read" kind="read" xpath="/cib"/>
      </acl_role>
      <acl_target id="monuser">
        <role id="read-only"/>
      </acl_target>
    </acls>
  </configuration>
</cib>

**Comment by fmherschel** [comment]
Hmm. I thought we had already solved that. Maybe a patch wasn't applied correctly. I will have a look on that, thanks for reporting.

**Comment by fdanapfel** [comment]
@fmherschel: is this really something that we can fix in the resource agent? 

As far as I understand the issue here is that while a backup is running on the HANA side the landscapeHostConfiguration.py script takes much longer to return than normal, so the only fix I could see for this issue would be to increase the timeout value of 60s that is currently hardcoded in the resource agent, which might have other side effects.

But in my opinion the correct solution here would be that SAP tries to figure out why the landscapeHostConfiguration.py script takes much longer than 60s to return in such situations, and to try to change it so that it returns much quicker even if a backup is running on the HANA side.

**Comment by khokarv** [comment]
Thanks for looking into this. 
Question: If database is responding slow, but working fine. As we noticed, around 120s. Timing out it within 60 second is misleading to say it's down. Is there any agreement or understand that landscape script must respond within 60s else consider DB to be down?

Though we are working SAP HANA team to look into this issue.

**Comment by fdanapfel** [comment]
@khokarv: as stated by SAP the landscapehostConfiguration.py script should normally only take a few seconds to run, therefore the timeout of 60s that the resource agents use was choosen with the assumption that this would be a large enough buffer in case the script might take longer.

The reason a timeout is set for the script is to avoid that the resource agent will hang forever in case the landscapehostConfiguration.py script does not return which would then cause any other cluster operations to be blocked and therefore render the cluster inoperable.

**Comment by khokarv** [comment]
@fdanapfel @fmherschel, Current version supports only 2 tier replication, Node A to Node B. We are doing something like 4 tier replication, do you have any timeline to support 4 tier replication?
Our Node A and B are local replication and Node C and D are at DR site. We are looking forward to use pacemaker SAPHana agent for 4 tier replication. Appreciate your help!

**Comment by fmherschel** [comment]
There is no timeline to be published public about 4tier replication.
However normally  to make sense a DR site is out of scope of a metro-cluster area and that fore even pacemaker would not be ready to build-up such a cluster. The most prominent problems are the high latency and timing.

For [ A=>B ] ---> [ C => D ] you would most like also need a GEO HA solution which could cover the
high latency and lower communication stability between DR sites.

**Comment by AnandTigadikar** [comment]
Hello,

We are looking to understand more with respect to Pacemaker support if we implement Multi-tier replication setup where Site A in primry will have 2 targets- B of Primary in form of syncmem and Site C in DR center via asycn replication mode.

We need to know -

1. Is it supported by PCS first of all ?
2. As we do understand, PCS looks only 2 sites in Primary DC, so although we do have 3rd or 4th site, will it impact in flawless Failover from Site-A to Site B?
3. If there are any lags and status in not Active for DR sync, will it cause just Failover in primary 2 sites -A to B?
4. There are some introduction of new parameters per below link and per it's recommendation, if we adopt them, should there by any concerns- since recommendation for us was to use enable_log_retention=on ?
https://help.sap.com/viewer/6b94445c94ae495c83a19646e7c3fd56/2.0.03/en-US/004f3015b0d4410b89084c7aa5e45dfe.html?q=enable_log_retention%20%3D%20force_on_takeover

-Also, recently per issue# 51 faced-- https://github.com/fmherschel/SAPHanaSR/issues/51 we are looking to implement this in appropriate and correct manner, so need further your advise and help.

Looking for some reply..
thanks,
Anand

**Comment by fmherschel** [comment]
Hi Anand,

you are asking for "support by PCS" - but what does that mean? You could only get support (as a 
process to resolve problems and to help you) by a HANA certified Linux vendor or a 3rd party HA software vendor. If you interpret the term "support" by "technical possible" the answer is that this has not been tested so far in the SAP LinuxLab. What has been tested so far is a replication between site A and B and
a second replication to site C. In such a case we switch-off the automated registration of a former primary
to get the new secondary. The SAPHanaSR solution 'only' automates a single SR and just ignores any additional SR.

Using SAPHanaSR  (for production with support) you need to have a valid subscription by one of the enterprise Linux distributors certified for HANA.

Regards
Fabian

**Comment by fdanapfel** [comment]
I agree with Fabian here, this needs to be handled via a Red Hat support case.
