### ISSUE TITLE
Failure in Failover even crm_mon -sync_state is SOK

### ISSUE THREAD

**Issue by AnandTigadikar** [fmherschel/SAPHanaSR-old-private#51]
Hello,

We have implemented 4 tier HANA system replication in HANA DB V2.03* where 2 sites are in Primary DC and we are using Pacemaker cluster tool for HA automatic Failover and rest 2 are in DR center.
We have implemented Pure chain replication -- A-->B-->C-->D and even for some DB Cluster -Multi-tier replication .
Now we are facing issue in either of replication scenario- 
1. when sometimes 4 tier sites are not in sync or active  , although sync_state in crm_mon is SOK  - we are seeing Failover from Site-A to Site B does not happen.

2. Need to know, entire output of python systemReplication script status is important for this Failover, although logically PCS should only understand 2 sites in HA for taking decision on Failover?

-Anand

**Comment by fdanapfel** [comment]
As already mentioned via mail it would be better to open a support case with Red Hat support for this, so that we can take a closer look at what exactly is happening here.
